#!/usr/bin/env julia
# PAM Perlmutter Installation Wrapper
# Sets Perlmutter-specific environment and delegates to generic scripts

@assert (Threads.nthreads() == 1) "Error: Installing PAM sysimage requires running Julia with one thread"

# Verify Perlmutter-specific required environment variables
@assert ("PAM_VERSION" in keys(ENV)) "Error: PAM_VERSION environment variable not set"
@assert ("PAM_BASE_DIR" in keys(ENV)) "Error: PAM_BASE_DIR environment variable not set"

# Get Perlmutter-specific variables
pam_version = ENV["PAM_VERSION"]
pam_base_dir = ENV["PAM_BASE_DIR"]
install_dir = ENV["PAM_INSTALL_DIR"]
pam_repo = ENV["PAM_REPO_DIR"]
cpu_target = get(ENV, "JULIA_CPU_TARGET", "generic;znver3,-xsaveopt,-rdrnd,clone_all")

println("### PAM Perlmutter Deployment: Version $pam_version")
println("")

# ===== Run Generic Installation Script =====
# Generic script handles all installation output and diagnostics
generic_install_script = joinpath(pam_repo, "deploy", "generic", "install_pam_env.jl")

if !isfile(generic_install_script)
    error("Generic installation script not found: $generic_install_script")
end

include(generic_install_script)

# ===== Perlmutter-Specific Post-Installation =====
println("")
println("### Perlmutter-specific setup")

import Dates

# Create Perlmutter module file from template
println("    Creating module file...")
module_file = joinpath(install_dir, "pam_module.lua")

# Read base template
base_lua = read(joinpath(@__DIR__, "base.lua"), String)

# Create header with variable definitions
module_header = """
-- PAM Module for Perlmutter
-- Auto-generated by PAM deployment script

local basedir = "$pam_base_dir"
local pam_version = "$pam_version"
local cpu_target = "$cpu_target"

help([[
PAM (Pellet Ablation Model) Environment
Version: ]] .. pam_version .. [[

This module provides a Julia environment with PAM and its dependencies
precompiled into an optimized system image for Perlmutter.

Usage:
  pam                    # Interactive REPL
  pam script.jl          # Run script
  pam -e 'using PAM; ...' # One-liner

Documentation: https://github.com/ProjectTorreyPines/PAM.jl
]])

"""

# Combine header + base template
write(module_file, module_header * base_lua)
println("    ✓ Module file: $module_file")

# Create Perlmutter environment info
println("    Creating Perlmutter info file...")
info_file = joinpath(install_dir, "PERLMUTTER_INFO.txt")

# Get node info
node_info = try
    read(`hostname`, String) |> strip
catch
    "unknown"
end

cpu_info = try
    cpu_model = readlines(pipeline(`lscpu`, `grep "Model name"`))
    length(cpu_model) > 0 ? split(cpu_model[1], ":")[2] |> strip : "unknown"
catch
    "unknown"
end

import Pkg
info_content = """
PAM Perlmutter Environment
==========================

Version:        $pam_version
Built on:       $(Dates.now())
Build node:     $node_info
Julia version:  $(VERSION)

CPU Target:     $cpu_target
CPU detected:   $cpu_info

Installation:
  Location:     $pam_base_dir/environments/$pam_version
  Module:       module load pam/$pam_version

Usage:
  module use $pam_base_dir/modules
  module load pam
  pam  # Start interactive REPL

Installed Packages:
-------------------
$(sprint(io -> Pkg.status(io=io)))
"""
write(info_file, info_content)
println("    ✓ Info file: $info_file")

println("")
println("### Perlmutter installation complete!")
println("    Module file: $module_file")
println("    Info file:   $info_file")
println("")
